# Generated by Django 4.2.9 on 2024-01-31 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('institution_intro', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('institution', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('budget', models.IntegerField(default=0, help_text='The amount of money that the member can spend on pets')),
                ('pet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.pet')),
            ],
        ),
        migrations.CreateModel(
            name='BigChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_status', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('institution', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.institution')),
            ],
        ),
    ]
