# Generated by Django 4.2.9 on 2024-01-31 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='pet',
        ),
        migrations.AddField(
            model_name='bigchart',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.member'),
        ),
        migrations.AddField(
            model_name='bigchart',
            name='pet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.pet'),
        ),
        migrations.AddField(
            model_name='bigchart',
            name='sign_up_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='members',
            field=models.ManyToManyField(default=None, related_name='attention_member', to='common.member'),
        ),
    ]
