# Generated by Django 4.2.9 on 2024-01-31 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_member_pet_bigchart_member_bigchart_pet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetMemberRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_status', models.CharField(max_length=100)),
                ('member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.member')),
                ('pet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.pet')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionPetRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_status', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.institution')),
                ('pet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.pet')),
            ],
        ),
    ]
