# Generated by Django 4.2.9 on 2024-01-31 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_petmemberrelationship_institutionpetrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpetrelationship',
            name='change_status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='institutionpetrelationship',
            name='signup_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='petmemberrelationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PetExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.pet')),
            ],
        ),
        migrations.CreateModel(
            name='MemberExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('member', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.member')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopt_condition', models.TextField()),
                ('follow_up_quality', models.TextField()),
                ('support_service', models.TextField()),
                ('successful_adoption_case', models.TextField()),
                ('pets_location', models.CharField(max_length=100)),
                ('donation_account', models.IntegerField()),
                ('chip_conversion_assitance', models.BooleanField(default=False)),
                ('dog_adoption_process', models.TextField(default=None)),
                ('cat_adoption_process', models.TextField(default=None)),
                ('institution', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.institution')),
            ],
        ),
    ]
