# Generated by Django 4.2.9 on 2024-01-29 04:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('institution_intro', models.CharField(max_length=150)),
                ('adopt_condition', models.TextField()),
                ('follow_up_quality', models.TextField()),
                ('support_service', models.TextField()),
                ('successful_adoption_case', models.TextField()),
                ('pets_location', models.CharField(max_length=100)),
                ('donation_account', models.IntegerField()),
                ('chip_conversion_assitance', models.BooleanField(default=False)),
                ('dog_adoption_process', models.TextField(default=None)),
                ('cat_adoption_process', models.TextField(default=None)),
                ('contact', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institutions.contact')),
            ],
        ),
    ]
