# Generated by Django 4.2.9 on 2024-01-31 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_remove_institution_contact_alter_institution_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='adopt_condition',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='cat_adoption_process',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='chip_conversion_assitance',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='dog_adoption_process',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='donation_account',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='follow_up_quality',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='pets_location',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='successful_adoption_case',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='support_service',
        ),
        migrations.CreateModel(
            name='InstitutionExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopt_condition', models.TextField()),
                ('follow_up_quality', models.TextField()),
                ('support_service', models.TextField()),
                ('successful_adoption_case', models.TextField()),
                ('pets_location', models.CharField(max_length=100)),
                ('donation_account', models.IntegerField()),
                ('chip_conversion_assitance', models.BooleanField(default=False)),
                ('dog_adoption_process', models.TextField(default=None)),
                ('cat_adoption_process', models.TextField(default=None)),
                ('institution', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='BigChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_status', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('institution', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
    ]
