# Generated by Django 4.2.9 on 2024-01-31 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_group_membership_person_delete_course_delete_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('budget', models.IntegerField(default=0, help_text='The amount of money that the member can spend on pets')),
            ],
        ),
        migrations.CreateModel(
            name='MemberExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('member', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
